/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaculdadeRouteImport } from './routes/faculdade'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as QuestoesRouteImport } from './routes/questoes'
import { Route as ResumosRouteImport } from './routes/resumos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaculdadeRoute = FaculdadeRouteImport.update({
  id: '/faculdade',
  path: '/faculdade',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestoesRoute = QuestoesRouteImport.update({
  id: '/questoes',
  path: '/questoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumosRoute = ResumosRouteImport.update({
  id: '/resumos',
  path: '/resumos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/faculdade': typeof FaculdadeRoute
  '/flashcards': typeof FlashcardsRoute
  '/historico': typeof HistoricoRoute
  '/perfil': typeof PerfilRoute
  '/questoes': typeof QuestoesRoute
  '/resumos': typeof ResumosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/faculdade': typeof FaculdadeRoute
  '/flashcards': typeof FlashcardsRoute
  '/historico': typeof HistoricoRoute
  '/perfil': typeof PerfilRoute
  '/questoes': typeof QuestoesRoute
  '/resumos': typeof ResumosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/faculdade': typeof FaculdadeRoute
  '/flashcards': typeof FlashcardsRoute
  '/historico': typeof HistoricoRoute
  '/perfil': typeof PerfilRoute
  '/questoes': typeof QuestoesRoute
  '/resumos': typeof ResumosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/faculdade'
    | '/flashcards'
    | '/historico'
    | '/perfil'
    | '/questoes'
    | '/resumos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/faculdade'
    | '/flashcards'
    | '/historico'
    | '/perfil'
    | '/questoes'
    | '/resumos'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/faculdade'
    | '/flashcards'
    | '/historico'
    | '/perfil'
    | '/questoes'
    | '/resumos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FaculdadeRoute: typeof FaculdadeRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HistoricoRoute: typeof HistoricoRoute
  PerfilRoute: typeof PerfilRoute
  QuestoesRoute: typeof QuestoesRoute
  ResumosRoute: typeof ResumosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculdade': {
      id: '/faculdade'
      path: '/faculdade'
      fullPath: '/faculdade'
      preLoaderRoute: typeof FaculdadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questoes': {
      id: '/questoes'
      path: '/questoes'
      fullPath: '/questoes'
      preLoaderRoute: typeof QuestoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumos': {
      id: '/resumos'
      path: '/resumos'
      fullPath: '/resumos'
      preLoaderRoute: typeof ResumosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FaculdadeRoute: FaculdadeRoute,
  FlashcardsRoute: FlashcardsRoute,
  HistoricoRoute: HistoricoRoute,
  PerfilRoute: PerfilRoute,
  QuestoesRoute: QuestoesRoute,
  ResumosRoute: ResumosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
