// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktaxdejdzdstssyhjtlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0YXhkZWpkemRzdHNzeWhqdGxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5ODY4MjYsImV4cCI6MjEwMTU2MjgyNn0.mZ7ry39YhcSMyOsFvyQR20RFnzEwuQJ4vju53Zf_gQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});